# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ldn62CbBaB6j9rU/U0bX+H4sW7FpPHd76tyU92/lHpdn81uv1TLGKmyQIE1RLrH3Q3YbLOH88n3Qzbbt6MmV8U366ZnhFWkXc37unl2ezUUsRk0FkuZX3I2FhzwM5Fjb0Ue+DIoYouTs9Q1WuS/ZsH6eG0hfphNANg2Xexs6v5MIRjAg8Gc4l8PBA54FP98b3H2r9gO0MaefTKCKZbsuI9YeuXWK6I6EDMmM5QntZtCw7DMAwEM56KqRHGFDyjZ5pETfw77++hr+YtdVOVSgOUpCzhWu1kGdvVbe7f0tYnm6iQ4BlVZTOuWpY6K2MMWpzneR9YFlie03kFGmLPujRRBbWRShbuynxSaV0lQEauXm5c2GqK+PqKP2vDYENECjXPAmXyB8iYifqCo/7b9VjjW+eGklKvwtMPeb51DU7f6Ju107y6qb7KK9dAf8lP3X5MNfAf6IJ3CL3Fv7m5jx6RDiyI3acLvvRyyQ1TjrX5EcXWRGuyzsdDxDKifZSTjsiYz4B+DryM2rkXBjvOmKhpahZYTvQ9TPrIVYEgtT9dYMj8sL4qBYcO2/ZSdc0Ji2TpGveRm46OxKEf2SvAtICpkRxH38U1kwzvACpkQBuSr9M64QlHqDWfxP9/HBPbM1reuEmaxMDE12s37TeU0hq8l3vlLF7+f5AKLZHwpW6sE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

      # install conda-build 2.x to build with a long prefix
      conda install --yes --quiet conda-build=2
      conda info

script:
  #################################################
  #              BEGIN CUSTOM CHANGE              #
  #                                               #
  # This change needs to stay intact on rerenders #
  #################################################

  # The build contains hardcoded references to the work directory in the
  # binary files. To fix this, we make the work directory exactly as long as
  # the placeholder prefix (255 characters.

  # The prefix ends with '/work/emacs-25.1' (16 characters). We put it in the
  #  miniconda3 directory, '/Users/travis/miniconda3/' (25 characters), so our
  # placeholder directory name needs 214 characters.

  - CONDA_BLD_PATH=/Users/travis/miniconda3/placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
  # We also need to set --no-build-id to avoid the recipe_1481871472196
  # subdirectory.
  - conda build --no-build-id ./recipe

  #################################################
  #              END CUSTOM CHANGE                #
  #################################################

  - upload_or_check_non_existence ./recipe conda-forge --channel=main

  # inspect the prefix lengths of the built packages
  - conda inspect prefix-lengths /Users/travis/miniconda3/conda-bld/osx-64/*.tar.bz2
